### ISSUE TITLE
大佬 刷到一定播放量之后就不能再刷，有解决办法了吗？

### ISSUE THREAD

**Issue by tiandao716** [Ven3/playcount#3]
我刚刷了一百多播放量就刷不动了，换IP也不行。
然后我去买了几百播放量，发现他们那机刷却还是可以继续刷，就是速度慢

**Comment by Ven3** [comment]
暂时还不能解决这个问题, 接口的方式是会有限制的, 或者你可以试试方式1, 用脚本+浏览器的方式, 这个是可以一直刷, 就是会稍微慢一点

**Comment by tiandao716** [comment]
嗯嗯 谢谢大佬。
